INSERT INTO TB_ESTADO (ID_ESTADO, DS_SIGLA) VALUES (1, 'MG');
INSERT INTO TB_CIDADE (ID_CIDADE, ID_ESTADO, DS_NOME) VALUES (1, 1, 'BELO HORIZONTE');
INSERT INTO TB_BAIRRO (ID_BAIRRO, ID_CIDADE, DS_NOME) VALUES (1, 1, 'CENTRO'), (2, 1, 'FUNCIONARIOS');

INSERT INTO TB_ENDERECO (ID_ENDERECO, EN_TIPO_LOCAL, DS_LOGRADOURO) VALUES (1, 'AVENIDA', 'AFONSO PENA');
INSERT INTO TB_COMPLEMENTO (ID_COMPLEMENTO, ID_ENDERECO, DS_DESCRICAO, NM_NUMERO) VALUES (1, 1, 'CASA', 3500), (2, 1, 'SALA COMERCIAL', 981);
INSERT INTO TB_CEP (ID_CEP, ID_ENDERECO, NM_NUMERO) VALUES (1, 1, 30130002), (2, 1, 30130008);

INSERT INTO TB_ENDERECO_BAIRRO (ID_ENDERECO, ID_BAIRRO) VALUES (1, 1); 
INSERT INTO TB_ENDERECO_BAIRRO (ID_ENDERECO, ID_BAIRRO) VALUES (1, 2); 